version: "3"

services:
  app:
    build: .
    command: >
      sh -c "npm install &&
             npm run build &&
             npm run start"
    env_file:
      - .env
    volumes:
      - .:/usr/app
